[project]
name = "llmapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pytest>=7.0.0",
    "requests>=2.28.0",
    "requests-mock>=1.12.1",
]
